### ISSUE TITLE
Query denoms by admin

### ISSUE THREAD

**Issue by fmorency** [strangelove-ventures/tokenfactory#24]
There's currently no way of listing denoms belonging to an admin (authority). One can only list denoms *created* by a given address.

Add the ability to list denoms by current admin (authority).

**Comment by fmorency** [comment]
cc @Reecepbcups

**Comment by Reecepbcups** [comment]
Yea I’ve had this in the todo for a while (since 2021)

Easy solution:
iterate all bank denoms in total supply with factory/ prefix, get admin, append to slice, return. Not state breaking due to being query only

Proper:
Create a new store index to save this as well. will require a store migration & be state breaking

We’ve deprioritized OSS work, so I can’t contribute here but happy to review a PR

**Comment by chalabi2** [comment]
> Yea I’ve had this in the todo for a while (since 2021)
> 
> Easy solution: iterate all bank denoms in total supply with factory/ prefix, get admin, append to slice, return. Not state breaking due to being query only
> 
> Proper: Create a new store index to save this as well. will require a store migration & be state breaking
> 
> We’ve deprioritized OSS work, so I can’t contribute here but happy to review a PR

That wont work because the admin can change but the denom stays the same
